"""
Scripting and automation tools.
Generates bash/python scripts and executes shell commands.
"""

import subprocess
import shlex


def generate_script(description: str, language: str = "bash") -> dict:
    """Generate an automation script based on a natural language description.

    The script content is generated with best practices:
    - Bash: Uses set -euo pipefail, includes error handling and comments.
    - Python: Uses proper exception handling, argparse, and logging.

    Note: This tool creates a script template. The agent's LLM generates the
    actual script content based on the description. This function provides
    the wrapper/boilerplate.

    Args:
        description: A natural language description of what the script should do
                     (e.g., 'rotate AWS IAM access keys for a user').
        language: The scripting language to use ('bash' or 'python'). Defaults to 'bash'.

    Returns:
        A dict with status and the generated script content with boilerplate.
    """
    if language == "bash":
        script = f"""#!/usr/bin/env bash
# ============================================================================
# Script: Generated automation script
# Description: {description}
# Generated by: DevOps Agent
# ============================================================================

set -euo pipefail

# ─── Configuration ──────────────────────────────────────────────────────────
LOG_FILE="/tmp/devops_script_$(date +%Y%m%d_%H%M%S).log"

# ─── Logging ────────────────────────────────────────────────────────────────
log() {{
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}}

error_exit() {{
    log "ERROR: $1"
    exit 1
}}

# ─── Main Logic ─────────────────────────────────────────────────────────────
main() {{
    log "Starting: {description}"

    # TODO: Implement the script logic for: {description}
    # The agent should fill in the actual commands here.

    log "Completed successfully"
}}

# ─── Entrypoint ─────────────────────────────────────────────────────────────
main "$@"
"""
    elif language == "python":
        script = f'''#!/usr/bin/env python3
"""
Generated automation script.
Description: {description}
Generated by: DevOps Agent
"""

import argparse
import logging
import sys
from datetime import datetime


# ─── Logging setup ──────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(f"/tmp/devops_script_{{datetime.now():%Y%m%d_%H%M%S}}.log"),
    ],
)
logger = logging.getLogger(__name__)


# ─── Main Logic ─────────────────────────────────────────────────────────────
def main(args):
    """Main entry point.

    Description: {description}
    """
    logger.info("Starting: {description}")

    try:
        # TODO: Implement the script logic for: {description}
        # The agent should fill in the actual logic here.
        pass

    except Exception as e:
        logger.error(f"Script failed: {{e}}", exc_info=True)
        sys.exit(1)

    logger.info("Completed successfully")


# ─── CLI ────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="{description}")
    # TODO: Add arguments as needed
    args = parser.parse_args()
    main(args)
'''
    else:
        return {
            "status": "error",
            "error": f"Unsupported language: {language}. Use 'bash' or 'python'.",
        }

    return {
        "status": "success",
        "language": language,
        "description": description,
        "script": script,
    }


def run_shell_command(command: str, timeout: int = 60) -> dict:
    """Execute a shell command and return the output.

    Args:
        command: The shell command to execute (e.g., 'ls -la /var/log' or 'df -h').
        timeout: Maximum seconds to wait for the command. Defaults to 60.

    Returns:
        A dict with status, stdout, stderr, and return_code.
    """
    try:
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return {
            "status": "success" if result.returncode == 0 else "error",
            "command": command,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
            "return_code": result.returncode,
        }
    except subprocess.TimeoutExpired:
        return {
            "status": "error",
            "command": command,
            "error": f"Command timed out after {timeout} seconds",
        }
    except Exception as e:
        return {
            "status": "error",
            "command": command,
            "error": str(e),
        }
